name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env: { POSTGRES_PASSWORD: pgpass, POSTGRES_DB: trendfind_test }
        ports: ["5432:5432"]
    env:
      DATABASE_URL: postgresql://postgres:pgpass@localhost:5432/trendfind_test
      FLASK_SECRET_KEY: dummy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: 3.10 }
      - run: pip install -r requirements.txt
      - run: pytest -q
