version: "3.9"
services:
  web:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, redis]
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: trendfind
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis:
    image: redis:7
  worker:
    build: .
    command: celery -A app.celery_app.celery worker -l info
    env_file: .env
    depends_on: [web, redis]
volumes:
  pgdata:
